services:
  rmq:
    image: rabbitmq:3-management-alpine
    container_name: rmq
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - nest-rabbit

networks:
  nest-rabbit:
    driver: bridge
